import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/layout/Header';
import { ReactNode } from 'react';
import ThemeProviderContent from '@/components/theme/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProviderContent>
          <Header />
          {children}
        </ThemeProviderContent>
      </body>
    </html>
  );
}
